joint_limits:
  joint_1:
    has_position_limits: true
    min_position: -0.7854
    max_position: 0.7854
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_effort_limits: false
    max_effort: 0.0
  joint_2:
    has_position_limits: true
    min_position: -0.6109
    max_position: 0.9599
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_effort_limits: false
    max_effort: 0.0
  joint_3:
    has_position_limits: true
    min_position: -1.2217
    max_position: 0.3491
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_effort_limits: false
    max_effort: 0.0
  joint_4:
    has_position_limits: true
    min_position: -0.1000
    max_position: 0.1000
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_effort_limits: false
    max_effort: 0.0
