robot_joint_publisher:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

robot_velocity_controller:
    type: "diff_drive_controller/DiffDriveController"
    publish_rate: 50
    left_wheel: 'front_left_wheel_joint'
    right_wheel: 'front_right_wheel_joint'
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    # Wheel separation and diameter. These are both optional. (readed from urdf)
    #wheel_separation: 0.16
    #wheel_radius: 0.032

    # Wheel separation and radius multipliers. These are both optional.
    wheel_separation_multiplier: 1.0 # default: 1.0
    #wheel_radius_multiplier: 1.0 # default: 1.0

    # Velocity commands timeout
    #cmd_vel_timeout: 0.25

    # Base frame_id (default: base_link)
    #base_frame_id: base_link 

    # Odometry fused with IMU is published by robot_localization, so
    # no need to publish a TF based on encoders alone.
    #enable_odom_tf: true

    # publish cmd_vel with limits
    publish_cmd: true

    # Velocity and acceleration limits
    linear:
        x:
            has_velocity_limits     : true
            max_velocity            : 0.3  # m/s
            #min_velocity            : -0.1  # m/s
            has_acceleration_limits : true
            max_acceleration        : 0.1 # m/s^2
            #min_acceleration        : 0.1 # m/s^2
            #has_jerk_limits         : true
            #max_jerk                : 5.0 # m/s^3

    angular:
        z:
            has_velocity_limits     : true
            max_velocity            : 0.4  # rad/s
            #min_velocity            : -0.1  # m/s
            has_acceleration_limits : true
            max_acceleration        : 0.1 # rad/s^2
            #min_acceleration        : 0.1 # m/s^2
            #has_jerk_limits         : true
            #max_jerk                : 5.0 # m/s^3
